export {default as Header } from './header/header'
export {default as Footer } from './footer/footer'
export {default as Hero} from './hero/hero'
export {default as Projects} from './projects/projects'
export {default as About} from './about/about'
export {default as Card} from './card/card'
export {default as Coming} from './coming/coming'